version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo npm install -g eslint jest --unsafe-perm=true
      - run: eslint .
      - run: jest
